### ISSUE TITLE
phar-build encounters fatal error after commit 1865248c18704731b55302b4044e7614136629cd

### ISSUE THREAD

**Issue by katanacrimson** [koto/phar-util#2] opened 2010-10-03 14:53 UTC
Upon executing phar-build:
    obsidian@lithion-mint ~/code/crcverify $ phar-build --phar verifier.phar
    PHP Fatal error:  Call to undefined method SplFileInfo::isDot() in /usr/bin/phar-build on line 161
    PHP Stack trace:
    PHP   1. {main}() /usr/bin/phar-build:0
    phar-build 0.5.3

```
Building Phar archive from ./src...
adding ./src/bootstrap.php
adding ./src/vendor
PHP Fatal error:  Call to undefined method SplFileInfo::isDot() in /usr/bin/phar-build on line 161
PHP Stack trace:
PHP   1. {main}() /usr/bin/phar-build:0
```

uname:
    obsidian@lithion-mint ~/code/crcverify $ uname -a
    Linux lithion-mint 2.6.32-21-generic #32-Ubuntu SMP Fri Apr 16 08:09:38 UTC 2010 x86_64 GNU/Linux

PHP info:
    obsidian@lithion-mint ~/code/crcverify $ php -v
    PHP 5.3.2-1ubuntu4.5 with Suhosin-Patch (cli) (built: Sep 17 2010 13:49:46) 
    Copyright (c) 1997-2009 The PHP Group
    Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
        with Xdebug v2.0.5, Copyright (c) 2002-2008, by Derick Rethans

If you need additional info, just ask.

**Comment by katanacrimson** [comment] 2010-10-03 14:54
...apologies, looks like github tried to get smart with the uname output.

**Comment by koto** [comment] 2010-10-03 17:53
Did you encounter this error with previous version (0.5.2) of the package? I've had some reports ( http://blog.kotowicz.net/2010/08/hardening-php-how-to-securely-include.html#c2123438661706515019 ) that suggested errors with dot directories under Linux (i'm using php 5.2 under linux and all was working ok for me) - so I've made this incorrect change. I wanted to use the  FilesystemIterator::SKIP_DOTS  flag for the iterator, but it's PHP 5.3 only.

Could you check for me if changing $file->isDot() to $iterator->isDot() fixes the issue for you? I can't reproduce this.

**Comment by katanacrimson** [comment] 2010-10-03 18:37
I did not have the problem with the previous version (I had just updated via pear today), but to fix it temporarily for myself, I just changed the isDot to this:
    substr($file, 0, 1) != '.'
It's hackish, but it works well enough.  I wanted to use $file[0], but as it is an object it's impossible.

I'll take a swing at $iterator real quick, though.  Will reply with results.

**Comment by katanacrimson** [comment] 2010-10-03 18:43
Seems to be working.  !$iterator->isDot() doesn't seem to be allowing any problematic results to be included, and isn't throwing any errors.

**Comment by koto** [comment] 2010-10-03 18:50
Then we're done with this - fixed in daeb346c90dbd0462db0d29bd2d165db94f26ef0 . 

btw - I'm really interested in how you use phar-util - drop me a note please, I've yet to receive any feedback from users ;)

**Comment by katanacrimson** [comment] 2010-10-03 18:58
I'm using it for a personal project, it's probably the simplest interface for working with phar that I've seen yet.  It's more or less to play with right now, until I find a serious use for it.

There's a few things that I've noticed that might be decent improvements, I'll open up an issue for each when I get the chance.

**Comment by koto** [comment] 2010-10-03 19:33
Please do. Also, you can always fork it and fix the issues in your code and then send me a pull request.

**Closed as completed** 2010-10-04 01:50 UTC
